### ISSUE TITLE
Robot Framework support

### ISSUE THREAD

**Issue by apallier** [chhantyal/code-syntax-highlighter#6]
Robot Framework highlighting doesn't seem to work.

Cases:

1. It is not mention in the drop down list
2. I tried "Detect language" item but highlighting was not correct

Please, could you add support of Robot Framework?

**Comment by chhantyal** [comment]
Hi @apallier , thank you for raising this ticket. You are right Robot framework is currently not supported. 

It's possible to add this feature. Since you are first person asking for this support, would you mind if you could send me short email with information like Is it private or company usage, how many users might use etc. You can write to me at nkchhantyal@gmail.com

Thanks

**Comment by apallier** [comment]
Done

**Comment by chhantyal** [comment]
New release `1.1.5-AC` adds support for RobotFramework. Thank you for this request 👍
